---
- name: check {{ fs.mount }}
  set_fact:
    my_bads: "{{ my_bads + [ fs.mount + ' needs ' + precheck_filesystems[ansible_distribution_major_version][fs.mount]|string + ' MB free space' ] }}"
  when:
    - fs.mount in precheck_filesystems[ansible_distribution_major_version]
    - fs.size_available < (precheck_filesystems[ansible_distribution_major_version][fs.mount] * 1024 * 1024)
