---
# tasks file for precheck

- name: Start with checking ssh ability
  include_tasks: ssh-check.yml
  tags: ssh

- name: Initialize an empty list for our warnings
  set_fact:
    my_bads: []
  tags: always

- name: Collecting minimal system information
  become: true
  setup:
    gather_subset: min
  tags: always

- name: Do basic mount checks.
  include_tasks: mounts.yml
  tags: mounts

- name: Check certain filesystems to make sure they have enough space
  include: filesystem_check.yml
  when:
    - precheck_filesystems is defined
    - precheck_filesystems | length > 0
  tags: filesystems

- block:
    - name: Collect output and display issues if anything is found
      tags: always
      vars:
        msg:
          - "{{ precheck_message | from_yaml }}"
          - "{{ my_bads }}"
      debug:
        msg: "{{ msg }}"

    - name: Fail here
      tags: always
      fail:
        msg:
          - "{{ precheck_fail_message | from_yaml }}"

  when: my_bads | length > 0
